### PR TITLE
Work

### PR DESCRIPTION
**Pull request by InAnYan**

### CODE REVIEW

**Comment by InAnYan** [comment]
@BigglesworthCat @SupperZum so.... the main app is done.

Bot: 

1) Writes messages to improve issues
2) Labels issues automatically

What should be done now:

1) Refactoring: get rid of `dyn` and `Arc<Mutex<..>>``
2) Better logging?
3) TESTING
4) Write better prompts for LLM, but before doing this, the 5th task should be done
5) Find a "real" repo to test the bot.

**Comment by InAnYan** [comment]
@BigglesworthCat @SupperZum, I don't know, will you believe or not, but I got rid of every `Arc<Mutex<...>>` and `dyn`

)))

**Review by BigglesworthCat — CHANGES_REQUESTED** [review]
Design looks great! I like the way you used Rust ecosystem instruments from using logging and using `thiserror` to event-based logic with `tokio`, `axum` and other crates.

Very cool👍.

But, for such large projects that require working with a third-party API, you should add a README.md with the requirements and necessary resources for customizing the bot yourself.
It would also be nice to see links to resources for using the API, such as connecting the bot to GitHub or how to get OpenAI token.

Also, it would be nice to run `cargo clippy` to see certain irrational constructions that increase the code input, such as in `match` constructions.

**Comment by InAnYan** [comment]
@BigglesworthCat should be better

**Comment by InAnYan** [comment]
@BigglesworthCat @SupperZum I've added tests

Should I add tests for `OpenAiLlm` and `GithubHost`?

**Comment by InAnYan** [comment]
@BigglesworthCat @SupperZum made all tests. Can you check please? 

Because I think I can ask for reviews very soon

**Review by niusia-ua — APPROVED** [review]
Cool project! I like this idea.

I have one point to note:
You have test data in the [githost](https://github.com/InAnYan/rust-gib/tree/work/src/githost/impls/github) implementation. You have placed it directly in the source code, so it looks like it is necessary for the project. But actually, it is used only in tests. It is better to mark it is used only for testing (e.g. place them under the `testdata` directory).

**Review by BigglesworthCat — APPROVED** [review]

**Review by divi255 — APPROVED** [review]

**Review by Dzuchun — APPROVED** [review]

**Review by SupperZum — APPROVED** [review]

**Review by ikripaka — APPROVED** [review]

**Pull request merged**
